tasks:
  - init: ./gradlew test
    command: 'echo "TODO: Replace with command to start project"'

vscode:
  extensions:
    - richardwillis.vscode-gradle@3.6.1:y4G3yqImY+P4qkY5ViQzZA==
    - nicoespeon.abracadabra@5.0.1:nlBnIXvpiR7u8TGxGGaUww==
    - kiteco.kite@0.142.0:HYAgyl8NGNwJ6eGqJrq1aw==
    - vscjava.vscode-java-test@0.28.1:Vq5tqFnbBv8CzIO03Hf19A==
    - pflannery.vscode-versionlens@1.0.9:MpYGqWwv0MK05mglx5q2Jg==