/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package logger;

import org.junit.Test;
import static org.junit.Assert.*;

public class LazyLoggerTest {
    @Test public void testSomeLibraryMethod() {
        LazyLogger classUnderTest = new LazyLogger();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
